---
version: "3.7"

services:

  oracle-db:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: oracle-db
    stop_grace_period: 5m
    env_file: wcc.env
    ports:
      - 1530:1521
    volumes:
      - ./scripts:/opt/oracle/scripts/setup
      - ./oradata:/opt/oracle/oradata

  oracle-wcc:
    image: oracle/wccontent:12.2.1.3
    container_name: oracle-wcc
    build:
      network: host
      context: ./images/wcc
    stop_grace_period: 5m
    env_file: wcc.env 
    ports:
      - 7001:7001
      - 16200:16200
